// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class LoginTest {
    private WebDriver driver;
    private Map<String, Object> vars;
    JavascriptExecutor js;
    @Before
    public void setUp() {
        driver = new FirefoxDriver();
        js = (JavascriptExecutor) driver;
        vars = new HashMap<String, Object>();
    }
    @After
    public void tearDown() {
        driver.quit();
    }
    @Test
    public void disabledLogin() {
        // Test name: DisabledLogin
        // Step # | name | target | value
        // 1 | open | / |
        driver.get("http://127.0.0.1:7000/");
        // 2 | setWindowSize | 550x584 |
        driver.manage().window().setSize(new Dimension(550, 584));
        // 3 | click | linkText=Sign in |
        driver.findElement(By.linkText("Sign in")).click();
        // 4 | click | id=sign-in__password |
        driver.findElement(By.id("sign-in__password")).click();
        // 5 | type | id=sign-in__password | Asfd@1234
        driver.findElement(By.id("sign-in__password")).sendKeys("Asfd@1234");
        // 6 | click | css=.form__button |
        driver.findElement(By.cssSelector(".form__button")).click();
        // 7 | click | id=sign-in__email |
        driver.findElement(By.id("sign-in__email")).click();
        // 8 | type | id=sign-in__email | araj
        driver.findElement(By.id("sign-in__email")).sendKeys("araj");
        // 9 | click | id=sign-in__password |
        driver.findElement(By.id("sign-in__password")).click();
        // 10 | type | id=sign-in__password | 1
        driver.findElement(By.id("sign-in__password")).sendKeys("1");
        // 11 | click | css=.form__button |
        driver.findElement(By.cssSelector(".form__button")).click();
    }
    @Test
    public void failedLogin() {
        // Test name: FailedLogin
        // Step # | name | target | value
        // 1 | open | / |
        driver.get("http://127.0.0.1:7000/");
        // 2 | setWindowSize | 550x584 |
        driver.manage().window().setSize(new Dimension(550, 584));
        // 3 | click | linkText=Sign in |
        driver.findElement(By.linkText("Sign in")).click();
        // 4 | click | id=sign-in__email |
        driver.findElement(By.id("sign-in__email")).click();
        // 5 | type | id=sign-in__email | araj
        driver.findElement(By.id("sign-in__email")).sendKeys("araj");
        // 6 | click | id=sign-in__password |
        driver.findElement(By.id("sign-in__password")).click();
        // 7 | type | id=sign-in__password | !23
        driver.findElement(By.id("sign-in__password")).sendKeys("!23");
        // 8 | click | css=.form__button |
        driver.findElement(By.cssSelector(".form__button")).click();
        // 9 | click | css=.form__heading |
        driver.findElement(By.cssSelector(".form__heading")).click();
        // 10 | mouseDownAt | id=sign-in__email | -44,15.316665649414062
        {
            WebElement element = driver.findElement(By.id("sign-in__email"));
            Actions builder = new Actions(driver);
            builder.moveToElement(element).clickAndHold().perform();
        }
        // 11 | mouseMoveAt | id=sign-in__email | -44,15.316665649414062
        {
            WebElement element = driver.findElement(By.id("sign-in__email"));
            Actions builder = new Actions(driver);
            builder.moveToElement(element).perform();
        }
        // 12 | mouseUpAt | id=sign-in__email | -44,15.316665649414062
        {
            WebElement element = driver.findElement(By.id("sign-in__email"));
            Actions builder = new Actions(driver);
            builder.moveToElement(element).release().perform();
        }
        // 13 | click | id=sign-in__email |
        driver.findElement(By.id("sign-in__email")).click();
        // 14 | type | id=sign-in__email | ARAJ
        driver.findElement(By.id("sign-in__email")).sendKeys("ARAJ");
        // 15 | click | css=.form__button |
        driver.findElement(By.cssSelector(".form__button")).click();
        // 16 | click | id=sign-in__email |
        driver.findElement(By.id("sign-in__email")).click();
        // 17 | mouseDownAt | id=sign-in__email | -16,13.316665649414062
        {
            WebElement element = driver.findElement(By.id("sign-in__email"));
            Actions builder = new Actions(driver);
            builder.moveToElement(element).clickAndHold().perform();
        }
        // 18 | mouseMoveAt | id=sign-in__email | -16,13.316665649414062
        {
            WebElement element = driver.findElement(By.id("sign-in__email"));
            Actions builder = new Actions(driver);
            builder.moveToElement(element).perform();
        }
        // 19 | mouseUpAt | id=sign-in__email | -16,13.316665649414062
        {
            WebElement element = driver.findElement(By.id("sign-in__email"));
            Actions builder = new Actions(driver);
            builder.moveToElement(element).release().perform();
        }
        // 20 | click | id=sign-in__email |
        driver.findElement(By.id("sign-in__email")).click();
        // 21 | type | id=sign-in__email | aRaJ
        driver.findElement(By.id("sign-in__email")).sendKeys("aRaJ");
        // 22 | click | css=.form__button |
        driver.findElement(By.cssSelector(".form__button")).click();
        // 23 | mouseDownAt | id=sign-in__email | -56,16.316665649414062
        {
            WebElement element = driver.findElement(By.id("sign-in__email"));
            Actions builder = new Actions(driver);
            builder.moveToElement(element).clickAndHold().perform();
        }
        // 24 | mouseMoveAt | id=sign-in__email | -56,16.316665649414062
        {
            WebElement element = driver.findElement(By.id("sign-in__email"));
            Actions builder = new Actions(driver);
            builder.moveToElement(element).perform();
        }
        // 25 | mouseUpAt | id=sign-in__email | -56,16.316665649414062
        {
            WebElement element = driver.findElement(By.id("sign-in__email"));
            Actions builder = new Actions(driver);
            builder.moveToElement(element).release().perform();
        }
        // 26 | click | id=sign-in__email |
        driver.findElement(By.id("sign-in__email")).click();
        // 27 | type | id=sign-in__email | Test
        driver.findElement(By.id("sign-in__email")).sendKeys("Test");
        // 28 | click | css=.form__button |
        driver.findElement(By.cssSelector(".form__button")).click();
    }
    @Test
    public void successfulLogin() {
        // Test name: SuccessfulLogin
        // Step # | name | target | value
        // 1 | open | / |
        driver.get("http://127.0.0.1:7000/");
        // 2 | setWindowSize | 550x692 |
        driver.manage().window().setSize(new Dimension(550, 692));
        // 3 | click | linkText=Sign in |
        driver.findElement(By.linkText("Sign in")).click();
        // 4 | click | id=sign-in__email |
        driver.findElement(By.id("sign-in__email")).click();
        // 5 | type | id=sign-in__email | asfd.asfd@example.com
        driver.findElement(By.id("sign-in__email")).sendKeys("asfd.asfd@example.com");
        // 6 | click | id=sign-in__password |
        driver.findElement(By.id("sign-in__password")).click();
        // 7 | type | id=sign-in__password | Asfd@1234
        driver.findElement(By.id("sign-in__password")).sendKeys("Asfd@1234");
        // 8 | click | css=.form__button |
        driver.findElement(By.cssSelector(".form__button")).click();
    }
}
