// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class LogoutFailtureTest {
    private WebDriver driver;
    private Map<String, Object> vars;
    JavascriptExecutor js;
    @Before
    public void setUp() {
        driver = new FirefoxDriver();
        js = (JavascriptExecutor) driver;
        vars = new HashMap<String, Object>();
    }
    @After
    public void tearDown() {
        driver.quit();
    }
    @Test
    public void successfulLogout() {
        // Test name: SuccessfulLogout
        // Step # | name | target | value
        // 1 | open | / |
        driver.get("http://127.0.0.1:7000/");
        // 2 | setWindowSize | 550x584 |
        driver.manage().window().setSize(new Dimension(550, 584));
        // 3 | click | linkText=Sign in |
        driver.findElement(By.linkText("Sign in")).click();
        // 4 | click | id=sign-in__email |
        driver.findElement(By.id("sign-in__email")).click();
        // 5 | type | id=sign-in__email | asfd.asfd@example.com
        driver.findElement(By.id("sign-in__email")).sendKeys("asfd.asfd@example.com");
        // 6 | click | id=sign-in__password |
        driver.findElement(By.id("sign-in__password")).click();
        // 7 | type | id=sign-in__password | Asfd@1234
        driver.findElement(By.id("sign-in__password")).sendKeys("Asfd@1234");
        // 8 | click | css=.form__button |
        driver.findElement(By.cssSelector(".form__button")).click();
        // 9 | click | css=.dropdown__link:nth-child(2) |
        driver.findElement(By.cssSelector(".dropdown__link:nth-child(2)")).click();
    }
}
