// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class ProfilefailtureTest {
    private WebDriver driver;
    private Map<String, Object> vars;
    JavascriptExecutor js;
    @Before
    public void setUp() {
        driver = new FirefoxDriver();
        js = (JavascriptExecutor) driver;
        vars = new HashMap<String, Object>();
    }
    @After
    public void tearDown() {
        driver.quit();
    }
    @Test
    public void viewProfile() {
        // Test name: ViewProfile
        // Step # | name | target | value
        // 1 | open | / |
        driver.get("http://127.0.0.1:7000/");
        // 2 | setWindowSize | 550x584 |
        driver.manage().window().setSize(new Dimension(550, 584));
        // 3 | click | linkText=My profile |
        driver.findElement(By.linkText("My profile")).click();
        // 4 | click | id=account__gender |
        driver.findElement(By.id("account__gender")).click();
    }
    @Test
    public void ediProfile() {
        // Test name: EdiProfile
        // Step # | name | target | value
        // 1 | open | / |
        driver.get("http://127.0.0.1:7000/");
        // 2 | setWindowSize | 550x584 |
        driver.manage().window().setSize(new Dimension(550, 584));
        // 3 | click | linkText=My profile |
        driver.findElement(By.linkText("My profile")).click();
        // 4 | click | id=account__first-name |
        driver.findElement(By.id("account__first-name")).click();
        // 5 | type | id=account__first-name | ashis
        driver.findElement(By.id("account__first-name")).sendKeys("ashis");
        // 6 | click | id=account__last-name |
        driver.findElement(By.id("account__last-name")).click();
        // 7 | type | id=account__last-name | raj
        driver.findElement(By.id("account__last-name")).sendKeys("raj");
        // 8 | click | id=account__gender |
        driver.findElement(By.id("account__gender")).click();
        // 9 | select | id=account__gender | label=Male
        {
            WebElement dropdown = driver.findElement(By.id("account__gender"));
            dropdown.findElement(By.xpath("//option[. = 'Male']")).click();
        }
        // 10 | click | css=option:nth-child(2) |
        driver.findElement(By.cssSelector("option:nth-child(2)")).click();
        // 11 | click | id=account__address |
        driver.findElement(By.id("account__address")).click();
        // 12 | type | id=account__address | E-605
        driver.findElement(By.id("account__address")).sendKeys("E-605");
        // 13 | click | id=account__website |
        driver.findElement(By.id("account__website")).click();
        // 14 | type | id=account__website | http://example.com
        driver.findElement(By.id("account__website")).sendKeys("http://example.com");
        // 15 | click | css=.button--fluid |
        driver.findElement(By.cssSelector(".button--fluid")).click();
        // 16 | click | css=.alert__button |
        driver.findElement(By.cssSelector(".alert__button")).click();
    }
}
