// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class RegistrationTest {
    private WebDriver driver;
    private Map<String, Object> vars;
    JavascriptExecutor js;
    @Before
    public void setUp() {
        driver = new FirefoxDriver();
        js = (JavascriptExecutor) driver;
        vars = new HashMap<String, Object>();
    }
    @After
    public void tearDown() {
        driver.quit();
    }
    @Test
    public void disabledRegistration() {
        // Test name: DisabledRegistration
        // Step # | name | target | value
        // 1 | open | / |
        driver.get("http://127.0.0.1:7000/");
        // 2 | setWindowSize | 550x692 |
        driver.manage().window().setSize(new Dimension(550, 692));
        // 3 | click | linkText=Sign up |
        driver.findElement(By.linkText("Sign up")).click();
        // 4 | click | id=sign-up__email |
        driver.findElement(By.id("sign-up__email")).click();
        // 5 | type | id=sign-up__email | asfd@example.com
        driver.findElement(By.id("sign-up__email")).sendKeys("asfd@example.com");
        // 6 | click | id=sign-up__password |
        driver.findElement(By.id("sign-up__password")).click();
        // 7 | type | id=sign-up__password | Asfd@1234
        driver.findElement(By.id("sign-up__password")).sendKeys("Asfd@1234");
        // 8 | click | id=sign-up__confirm-password |
        driver.findElement(By.id("sign-up__confirm-password")).click();
        // 9 | type | id=sign-up__confirm-password | Asfd@1234
        driver.findElement(By.id("sign-up__confirm-password")).sendKeys("Asfd@1234");
        // 10 | click | css=.form__button |
        driver.findElement(By.cssSelector(".form__button")).click();
        // 11 | click | id=sign-up__first-name |
        driver.findElement(By.id("sign-up__first-name")).click();
        // 12 | type | id=sign-up__first-name | asfd
        driver.findElement(By.id("sign-up__first-name")).sendKeys("asfd");
        // 13 | click | id=sign-up__email |
        driver.findElement(By.id("sign-up__email")).click();
        // 14 | type | id=sign-up__email |
        driver.findElement(By.id("sign-up__email")).sendKeys(" ");
        // 15 | click | css=.form__button |
        driver.findElement(By.cssSelector(".form__button")).click();
        // 16 | click | id=sign-up__email |
        driver.findElement(By.id("sign-up__email")).click();
        // 17 | type | id=sign-up__email | asfd
        driver.findElement(By.id("sign-up__email")).sendKeys("asfd");
        // 18 | click | id=sign-up__last-name |
        driver.findElement(By.id("sign-up__last-name")).click();
        // 19 | type | id=sign-up__last-name | asfd
        driver.findElement(By.id("sign-up__last-name")).sendKeys("asfd");
        // 20 | click | css=.form__button |
        driver.findElement(By.cssSelector(".form__button")).click();
        // 21 | click | css=.form__heading |
        driver.findElement(By.cssSelector(".form__heading")).click();
        // 22 | click | id=sign-up__email |
        driver.findElement(By.id("sign-up__email")).click();
        // 23 | type | id=sign-up__email | asfd.asfd@example.com
        driver.findElement(By.id("sign-up__email")).sendKeys("asfd.asfd@example.com");
        // 24 | click | css=.form__button |
        driver.findElement(By.cssSelector(".form__button")).click();
        // 25 | click | css=.alert__button |
        driver.findElement(By.cssSelector(".alert__button")).click();
        // 26 | click | id=sign-up__password |
        driver.findElement(By.id("sign-up__password")).click();
        // 27 | type | id=sign-up__password | Asfd@1234
        driver.findElement(By.id("sign-up__password")).sendKeys("Asfd@1234");
        // 28 | click | css=.form__button |
        driver.findElement(By.cssSelector(".form__button")).click();
    }
    @Test
    public void successfulRegistration() {
        // Test name: SuccessfulRegistration
        // Step # | name | target | value
        // 1 | open | / |
        driver.get("http://127.0.0.1:7000/");
        // 2 | setWindowSize | 550x584 |
        driver.manage().window().setSize(new Dimension(550, 584));
        // 3 | click | linkText=Sign up |
        driver.findElement(By.linkText("Sign up")).click();
        // 4 | click | id=sign-up__first-name |
        driver.findElement(By.id("sign-up__first-name")).click();
        // 5 | type | id=sign-up__first-name | asfd
        driver.findElement(By.id("sign-up__first-name")).sendKeys("asfd");
        // 6 | click | id=sign-up__last-name |
        driver.findElement(By.id("sign-up__last-name")).click();
        // 7 | type | id=sign-up__last-name | asfd
        driver.findElement(By.id("sign-up__last-name")).sendKeys("asfd");
        // 8 | click | id=sign-up__email |
        driver.findElement(By.id("sign-up__email")).click();
        // 9 | type | id=sign-up__email | asfd@example.com
        driver.findElement(By.id("sign-up__email")).sendKeys("asfd@example.com");
        // 10 | click | id=sign-up__password |
        driver.findElement(By.id("sign-up__password")).click();
        // 11 | type | id=sign-up__password | Asfd@1234
        driver.findElement(By.id("sign-up__password")).sendKeys("Asfd@1234");
        // 12 | click | css=.form__button |
        driver.findElement(By.cssSelector(".form__button")).click();
        // 13 | click | id=sign-up__confirm-password |
        driver.findElement(By.id("sign-up__confirm-password")).click();
        // 14 | type | id=sign-up__confirm-password | Asfd@1234
        driver.findElement(By.id("sign-up__confirm-password")).sendKeys("Asfd@1234");
        // 15 | click | css=.form__button |
        driver.findElement(By.cssSelector(".form__button")).click();
        // 16 | click | css=.alert__button |
        driver.findElement(By.cssSelector(".alert__button")).click();
    }
}
