name: reviewdog
on: 
  push:
      branches: [ "master" ]
jobs:
  checkstyle:
    name: runner / checkstyle
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: GitCyberMaster/action-checkstyle@v0.9.5
        with:
          github_token: ${{ secrets.github_token }}
          reporter: github-pr-review
          level: warning
